#! /bin/sh

set -e

# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi



# System-Services:
# put in full unit-name. for example "mkbackup@hourly.service"
#SERVICES="mkbackup.target backup.automount var-cache-backup.automount btrfs-scrub@var-cache-btrfs_pool_SYSTEM.service mkbackup@manually.service mkbackup@aptupgrade.service mkbackup@daily.service mkbackup@weekly.service mkbackup@monthly.service mkbackup@plugin.service mkbackup@manually.service"
SERVICES="
        fetchnews.timer
        "
INSTSERVICES="
"

case "$1" in
    purge)
	if [ -x "/usr/bin/deb-systemd-helper-new" ]; then
		deb-systemd-helper-new purge $SERVICES $INSTSERVICES $CINT >/dev/null
		deb-systemd-helper-new unmask $SERVICES $INSTSERVICES $CINT >/dev/null
	fi
        ;;
    abort-upgrade)
        ;;
    remove)
        if [ -x "/usr/bin/deb-systemd-helper-new" ]; then
                deb-systemd-helper-new mask $SERVICES $INSTSERVICES $CINT >/dev/null
        fi
        ;;
    upgrade|failed-upgrade|abort-install|disappear)
        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 0
        ;;

esac
